config/routes.rb
Swap::Application.routes.draw do
  resources :accessory_items

  resources :carts

  get "store/index"
  resources :accessories

  root 'store#index', as: "store"

end

app/models/accessory.rb
class Accessory < ActiveRecord::Base
	has_many :accessory_items
	validates :item, :platform, :description, :price,  :stock, presence: true

    
	validates :item, uniqueness: true
	validates :stock, numericality: { only_integer: true}
	validates :price, numericality: { greater_than_or_equal_to: 0.01}
	if Rails.env.development?
  	    has_attached_file :poster, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "default.jpg"
    else
    	has_attached_file :poster, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "default.jpg",
	                           :storage => :dropbox,
                               :dropbox_credentials => Rails.root.join("config/dropbox.yml")
    end
        validates_attachment_content_type :poster, :content_type => /\Aimage\/.*\Z/
 end

app/models/accessory_item.rb
class AccessoryItem < ActiveRecord::Base
	belongs_to :cart
	belongs_to :accessory
end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :accessory_items, dependent: :destroy
end

app/controllers/accessories_controller.rb
class AccessoriesController < ApplicationController
  before_action :set_accessory, only: [:show, :edit, :update, :destroy]
  respond_to :html
  # GET /accessories
  # GET /accessories.json
  def index
    @accessories = Accessory.all
  end

  # GET /accessories/1
  # GET /accessories/1.json
  def show
  end

  # GET /accessories/new
  def new
    @accessory = Accessory.new
  end

  # GET /accessories/1/edit
  def edit
  end

  # POST /accessories
  # POST /accessories.json
  def create
    @accessory = Accessory.new(accessory_params)

    respond_to do |format|
      if @accessory.save
        format.html { redirect_to @accessory, notice: 'Accessory was successfully created.' }
        format.json { render action: 'show', status: :created, location: @accessory }
      else
        format.html { render action: 'new' }
        format.json { render json: @accessory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accessories/1
  # PATCH/PUT /accessories/1.json
  def update
    respond_to do |format|
      if @accessory.update(accessory_params)
        format.html { redirect_to @accessory, notice: 'Accessory was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @accessory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accessories/1
  # DELETE /accessories/1.json
  def destroy
    @accessory.destroy
    respond_to do |format|
      format.html { redirect_to accessories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_accessory
      @accessory = Accessory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def accessory_params
      params.require(:accessory).permit(:item, :platform, :description, :price, :stock, :poster)
    end
end

app/controllers/accessory_items_controller.rb
class AccessoryItemsController < ApplicationController
  before_action :set_accessory_item, only: [:show, :edit, :update, :destroy]
  respond_to :html

  def index
    @accessory_items = AccessoryItem.all
  end

  def shows
  end

  def new
    @accessory_item = AccessoryItem.new
  end

  def edit
  end

  def create
    @accessory_item = @cart.accessory_items.find_or_initialize_by_movie_id(accessory_id: params[:accessory_id],:quantity=>0 )
    @accessory_item.quantity += 1
    respond_to do |format|
      if @accessory_item.save
        format.html { redirect_to @accessory_item.cart, notice: "#{@accessory_item.accessory.item} was successfully added to cart." }
        format.json { render action: 'show', status: :created, location: @accessory_item }     
      else
        format.html { render action: 'new' }
        format.json { render json: @accessory_item.errors, status: :unprocessable_entity}
      end
    end
  end

  def update
    @accessory_item = AccessoryItem.find(params[:id])
    respond_to do |format|
      if params[:accessory_item][:quantity].to_i == 0
        @accessory_item.destroy
        format.html { redirect_to @accessory_item.cart, notice: "#{@accessory_item.accessory.item} removed"}
        format.json { head :no_content }
      elsif @accessory_item.update(accessory_item_params),
        format.html { redirect_to @accessory_item.cart, notice: "#{@accessory_item.accessory.item} successfully updated by #{@accessory_item.quantity}." }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @accessory_item.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
   @accessory_item.destroy
    respond_to do |format|
      format.html { redirect_to @accessory_item.cart } 
      format.json { head :no_content}
    end
  end

  private
    def set_accessory_item
      @accessory_item = AccessoryItem.find(params[:id])
    end

    def accessory_item_params
      params.require(:accessory_item).permit(:accessory_id, :cart_id, :quantity)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  respond_to :html

  def index
    @carts = Cart.all
    respond_with(@carts)
  end

  def show
    respond_with(@cart)
  end

  def new
    @cart = Cart.new
    respond_with(@cart)
  end

  def edit
  end

  def create
    @cart = Cart.new(cart_params)
    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render action: 'show', status: :created, location: @cart }
      else
        format.html { render action: 'new'}
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end 
  end

  def update
   @cart.update(cart_params)
    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully update.' }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end 
  end

  def destroy
     @cart.destroy
    respond_to do |format|
      format.html { redirect_to store_path }
      format.json { head :no_content }
    end
  end

  private
    def set_cart
      @cart = Cart.find(params[:id])
    end

    def cart_params
      params.require(:cart).permit(:user_id)
    end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
  	@accessories= Accessory.all
  end
end

app/helpers/accessories_helper.rb
module AccessoriesHelper
	def check_stock(stock)
		if stock == 0
			content_tag(:span, "Out of Stock", class: "out_stock")
		else
			content_tag(:span, "In stock", class: "in_stock")
		end
	end

	def check_price(price)
	  number_to_currency price
	end
 end

app/helpers/accessory_items_helper.rb
module AccessoryItemsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def flash_message(type)
		type == :notice ? "alert-success" : "alert-warning"
		# case type
		# when :notice
		# 	"alert-success"
	 #    when :alert
	 #    	"alert-warning"
	 #    else
	 #       ""
	 #    end
	 end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/accessories/_form.html.erb
<%= form_for(@accessory,:html => { :multipart => true}) do |f| %>
  <% if @accessory.errors.any? %>
<div id="error_explanation", class="alert alert-danger alert dismissible">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>     
     <h2><%= pluralize(@accessory.errors.count, "error") %> prohibited this accessory from being saved:</h2>

      <ul>
      <% @accessory.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :item %>
    <%= f.text_field :item,class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :platform %>
    <%= f.text_field :platform,class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description,class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :price %>
    <%= f.text_field :price,class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :stock %>
    <%= f.text_field :stock,class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :poster %>
    <%= f.file_field :poster,class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-success custom-btn access" %>
  </div>
<% end %>

app/views/accessories/edit.html.erb
<div class="container">
<h1>Editing accessory</h1>

<%= render 'form' %>

<%= link_to 'Show', @accessory %> |
<%= link_to 'Back', accessory_path %> |
</div>

app/views/accessories/index.html.erb
<div class="container">
<h1>All Accessories</h1>

<table class="table table-responsive">
 s<thead>
    <tr>
      <th>Image</th>
      <th>Item</th>
      <th>Platform</th>
      <th>Description</th>
      <th>Price</th>
      <th>Stock</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @accessories.each do |accessory| %>
      <tr>
       <td><%= image_tag accessory.poster.url(:medium),class: "img-responsive" %></td>
        <td><%= accessory.item %></td>
        <td><%= accessory.platform %></td>
        <td><%= accessory.description %></td>
        <td><%= accessory.price %></td>
        <td><%= accessory.stock %></td>
        <td><%= link_to 'Show', accessory %></td>
        <td><%= link_to 'Edit', edit_accessory_path(accessory) %></td>
        <td><%= link_to 'Destroy', accessory, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Accessory', new_accessory_path %>
</div>s

app/views/accessories/new.html.erb
<div class="container">
<h1>New accessory</h1>

<%= render 'form' %>

<%= link_to 'Back', accessories_path %>
</div>

app/views/accessories/show.html.erb
<div class="container">
  <div class="row">
      <div class="col-md-3">
       <%= image_tag(@accessory.poster.url, class: "img-responsive")%>
       </div>
       <div class="col-md-9">
         <h2><%= @accessory.item %> (<%= @accessory.platform %>)</h2>
         <p><%= @accessory.description %></p> 
              </div>
        <p>Price: <span class="accessory_price"><%= @accessory.price %></span>
           <%= link_to 'Back', store_path %></p>
           <p><%= button_to "Add to Cart", accessory_items_path(accessory_id: @accessory.id), class: "btn btn-success btn-lg custom-btn pull-right"%></p>
      </div>
  </div>
</div>

app/views/accessory_items/_form.html.erb
<%= form_for(@accessory_item) do |f| %>
  <% if @accessory_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@accessory_item.errors.count, "error") %> prohibited this accessory_item from being saved:</h2>

      <ul>
      <% @accessory_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :accessory_id %><br>
    <%= f.number_field :accessory_id %>
  </div>
  <div class="field">
    <%= f.label :cart_id %><br>
    <%= f.number_field :cart_id %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/accessory_items/edit.html.erb
<h1>Editing accessory_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @accessory_item %> |
<%= link_to 'Back', accessory_items_path %>

app/views/accessory_items/index.html.erb
<h1>Listing accessory_items</h1>

<table>
  <thead>
    <tr>
      <th>Accessory</th>
      <th>Cart</th>
      <th>Quantity</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @accessory_items.each do |accessory_item| %>
      <tr>
        <td><%= accessory_item.accessory_id %></td>
        <td><%= accessory_item.cart_id %></td>
        <td><%= accessory_item.quantity %></td>
        <td><%= link_to 'Show', accessory_item %></td>
        <td><%= link_to 'Edit', edit_accessory_item_path(accessory_item) %></td>
        <td><%= link_to 'Destroy', accessory_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Accessory item', new_accessory_item_path %>

app/views/accessory_items/new.html.erb
<h1>New accessory_item</h1>

<%= render 'form' %>

<%= link_to 'Back', accessory_items_path %>

app/views/accessory_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Accessory:</strong>
  <%= @accessory_item.accessory_id %>
</p>

<p>
  <strong>Cart:</strong>
  <%= @accessory_item.cart_id %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @accessory_item.quantity %>
</p>

<%= link_to 'Edit', edit_accessory_item_path(@accessory_item) %> |
<%= link_to 'Back', accessory_items_path %>

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<h1>Listing carts</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= cart.user_id %></td>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @cart.user_id %>
</p>

<%= link_to 'Edit', edit_cart_path(@cart) %> |
<%= link_to 'Back', carts_path %>

app/views/layouts/_footer.html.erb
<footer class="row">
   <div class="col-sm-12"> 
   <p>&copy; Swap <%= Time.now.year %></p>
   </div>
</footer>
   

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Swap", store_path, class: "navbar-brand main-logo" %>
    </div>
      

     

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Register", "#" %></li>
        <li><%= link_to "Login", "#" %></li>
        </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_messages.html.erb
<% if flash.each do |type, message| %>
  	<div class="alert <%= flash_message type %> alert-dismissible" role="alert">
  	<button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
  	  <%= message %>
  	</div>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Swap</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "layouts/header" %>
<div class="container">
<% if flash.each do |type, message| %>
  	<div class="alert <%= flash_message type %> alert-dismissible" role="alert">
  	<button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
  	  <%= message %>
  	</div>
  <% end %>
</div> 

<%= yield %>

<div class="container">
  <%= render "layouts/footer" %>

</div>
</body>
</html>

<% end %>

app/views/store/index.html.erb
<div class="jumbotron">
  <div class="text-center">
    <h2>Welcome to <span id="app">Swap</span></h2>
    <p><strong>Buy</strong>, <strong>sell</strong> and <strong>swap</strong> your game accessories. <br> 
    Find the latest game stations and titles in just a click.</p>
    <p><strong>Sign up</strong> using Facebook or Twitter</p>
    <p><%= link_to "Facebook", "#", class: "btn btn-primary btn-lg custom-btn-lg" %> <%= link_to "Twitter", "#", class: "btn btn-info btn-lg custom-btn-lg" %> <br> <span class="non-social"><strong>Don't use them?</strong> <ins><%= link_to "Sign up", "#" %></ins> with your email address.</span></p>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h4 class="tpad text-capitalize">Featured Accessories</h4>
    </div>
  </div>
  <div class="row">
    <% @accessories.each do |accessory| %>
      <div class="col-md-3">
        <div class="panel panel-default">
          <div class="panel-heading">
          <%= link_to image_tag(accessory.poster.url, class: "img-responsive"),accessory%>
          </div>
          <div class="panel-body">
            <h4 class="text-center"><%= accessory.item %> (<%= accessory.platform %>)</h4>
            <p><%= check_stock accessory.stock %><span class="accessory_price pull-right"><%= check_price accessory.price %></span></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>